name: Build documentation

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r doc/requirements.txt
    - name: Build sphinx documentation
      run: |
        make -C doc html
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: doc/_build/html # The folder the action should deploy.
